# Fly.io configuration for the portfolio app

app = "portfolio-website"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  NODE_ENV = "production"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.http_checks]]
    interval = "10s"
    grace_period = "10s"
    method = "get"
    path = "/"
    protocol = "http"
    timeout = "2s"

  [services.http_options]
    h2_backend = true

  [checks]
    [checks.alive]
      type = "http"
      port = 8080
      interval = "15s"
      timeout = "2s"
      method = "get"
      path = "/"

